version: '3.8'

services:
  bitespeed-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./contacts.db:/app/contacts.db
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    driver: bridge