services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./contacts.db
      - key: PYTHON_VERSION
        value: 3.11.0